### ISSUE TITLE
Are the data available?

### ISSUE THREAD

**Issue by aarsri** [KiroSummer/Syntax-aware-Neural-SRL#1]
Hello,

./Syntax-aware-DeepSRL-w-ELMo/exp-Tree-GRU-w-ELMo/ points to a data folder.  Are the data available anywhere?

Thank you!

**Comment by KiroSummer** [comment]
Hi,
This directory means the experiment of SRL with the TreeGRU method and ELMo representations. I provide the config file in it. For the SRL data, you can refer to https://github.com/luheng/deep_srl. For the auto dependency file, you should train a dependency parser and then parse the SRL data with the trained model. For the ELMo representations, you can download and use it from https://allennlp.org/elmo. Besides, the SRL (CoNLL-05) and dependency file (PTB) are not publicly available, you can download it from LDC.
